#!/usr/bin/env bash
# vim: ft=bash ts=4

WD=`pwd`
SD=`dirname $0`

. ~/.config/cfgkeeperrc

vcs=`basename $VCS`
. $SD/cfgkeeper.${vcs##.*}	

_add(){
	local fp=$1
	if [ ! "${fp:0:1}" = "/" ]; then
		fp=$(cd $(dirname "$WD/$fp"); pwd -P)/$(basename "$fp")
	fi

	if [ -f "$fp" ]; then
		local dp="$BAKDIR`dirname "$fp"`"
		mkdir -p "$dp"
		dp=$dp/`basename "${1}"`
		cp -dp "$fp" "$dp"
		vcs_add "${fp#/}"
		[ $? = 0 ] && echo "add $fp"
	elif [ -d "$1" ]; then
		echo "error: add files separately."
	fi

	return 0
}

_rm(){
	local fp=$1
	if [ ! "${fp:0:1}" = "/" ]; then
		fp=$(cd $(dirname "$WD/$fp"); pwd -P)/$(basename "$fp")
	fi

	if [ -f "${BAKDIR}${fp}" ]; then
		vcs_rm "${fp#/}"
	elif [ -d "${BAKDIR}${fp}" ]; then
		echo "error: remove files separatley."
	fi
	
	return 0
}

_commit(){
	vcs_commit "${1}"
	[ 0 = $? ] && echo "set commited." 
}

_usage(){
	echo -en "usage: $(basename $0)\n"
	echo -en "   add FILE\tAdd a file to the commit set\n"
	echo -en "   rm FILE\tRemove a file from the backup\n"
	echo -en "   commit MSG\tRecord changes to the repository\n"
	echo -en "   status\tShow the repositors status\n"
	echo -en "   check\tShow tracked file changes\n"
	echo -en "   *\t\tForward arguments to $vcs\n"
	echo -en "\n"
}

_check(){
	echo "TODO check"
}

[ $# = 0 ] && _usage && exit

case "$1" in
	add)	[ $# = 2 ] && _add "$2" || _usage;;

	rm)		[ $# = 2 ] && _rm "$2" || _usage;;

	commit)	[ $# = 2 ] && _commit "$2" || _usage;;

	status)	vcs_status;;

	check)	_check;;

	*)		vcs_pt $@;;
esac

