#!/usr/bin/env bash
# vim: ft=bash ts=4

WD=$PWD
SD=`dirname $0`
FP=''

. ~/.config/cfgkeeperrc

vcs=`basename $VCS`
. $SD/cfgkeeper.${vcs##.*}	


_setFP(){
	FP=$1
	if [ ! "${FP:0:1}" = "/" ]; then
		FP=$(cd $(dirname "$WD/$FP"); pwd -P)/$(basename "$FP")
	fi
}

_add(){
	_setFP "$1"
	if [ -f "$FP" ]; then
		local dp="$BAKDIR`dirname "$FP"`"
		mkdir -p "$dp"
		dp=$dp/`basename "${1}"`
		cp -dp "$FP" "$dp"
		vcs_add "${FP#/}"
		[ $? = 0 ] && echo "add $FP"
	elif [ -d "$1" ]; then
		echo "error: add files separately."
	fi

	return 0
}

_rm(){
	_setFP "$1"
	if [ -f "${BAKDIR}${FP}" ]; then
		vcs_rm "${FP#/}"
	elif [ -d "${BAKDIR}${FP}" ]; then
		echo "error: remove files separatley."
	fi
	
	return 0
}

_commit(){
	vcs_commit "${1}"
	[ 0 = $? ] && echo "set commited." 
}

_usage(){
	echo -en "usage: $(basename $0)\n"
	echo -en "   add FILE\t\tAdd a file to the commit set\n"
	echo -en "   rm FILE\t\tRemove a file from the repository\n"
	echo -en "   commit MSG\t\tRecord changes to the repository\n"
	echo -en "   status [ARGS]\t\tShow the repository status\n"
	echo -en "   check\t\tShow modified files\n"
	echo -en "   ARGS\t\t\tForward arguments to $vcs\n"
	echo -en "\n"
	exit 1
}

_check(){
	echo "TODO check"
}

[ $# = 0 ] && _usage && exit

case "$1" in
	add)	[ $# -gt 1 ] && shift && _add "$1" || _usage;;

	rm)	[ $# -gt 1 ] && shift && _rm "$1" || _usage;;

	commit)	[ $# -gt 1 ] && shift && _commit "$1" || _usage;;

	status)	shift; vcs_status $@;;

	check)	_check;;

	*)	vcs_pt $@;;
esac

